openapi: 3.0.3
info:
  title: Caller Name (CNAM)
  description: >-
    The Bandwidth Caller Name (CNAM) API can be used to retrieve caller-name
    information for a calling number via a

    single on-demand HTTP dip.


    Each dip is billed at a flat rate unless the `dryRun` query parameter is set
    to `true`, in which case a placeholder

    name is returned and the dip is not billed.
  contact:
    name: Bandwidth
    url: https://support.bandwidth.com
    email: support@bandwidth.com
  termsOfService: https://www.bandwidth.com/legal/terms-of-use-bandwidthcom-web-sites/
  version: 1.0.0
servers:
  - url: https://api.bandwidth.com/api/v1
    description: Production
paths:
  /accounts/{accountId}/cnam/phone-numbers/{phoneNumber}:
    get:
      tags:
        - CNAM
      summary: Retrieve Caller Name Information
      description: >-
        Retrieve caller-name information for a calling number via a single
        on-demand HTTP dip.


        Set the `dryRun` query parameter to `true` to perform a dry run. A dry
        run returns a placeholder name and the

        dip is not billed.
      operationId: getCnam
      parameters:
        - $ref: '#/components/parameters/accountId'
        - $ref: '#/components/parameters/phoneNumber'
        - $ref: '#/components/parameters/dryRun'
      responses:
        '200':
          $ref: '#/components/responses/cnamInfoResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '403':
          $ref: '#/components/responses/forbiddenResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '405':
          $ref: '#/components/responses/methodNotAllowedResponse'
        '429':
          $ref: '#/components/responses/tooManyRequestsResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  parameters:
    accountId:
      name: accountId
      schema:
        $ref: '#/components/schemas/accountId'
      in: path
      required: true
    phoneNumber:
      name: phoneNumber
      schema:
        $ref: '#/components/schemas/phoneNumber'
      in: path
      required: true
    dryRun:
      name: dryRun
      schema:
        $ref: '#/components/schemas/dryRun'
      in: query
      required: false
  responses:
    cnamInfoResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/cnamInfo'
          examples:
            cnamInfoExample:
              $ref: '#/components/examples/cnamInfoExample'
    badRequestResponse:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/apiErrors'
          examples:
            badRequestExample:
              $ref: '#/components/examples/badRequestErrorExample'
    unauthorizedResponse:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/apiErrors'
          examples:
            unauthorizedExample:
              $ref: '#/components/examples/unauthorizedErrorExample'
    forbiddenResponse:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/apiErrors'
          examples:
            forbiddenExample:
              $ref: '#/components/examples/forbiddenErrorExample'
    notFoundResponse:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/apiErrors'
          examples:
            notFoundExample:
              $ref: '#/components/examples/notFoundErrorExample'
    methodNotAllowedResponse:
      description: Method Not Allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/apiErrors'
          examples:
            methodNotAllowedExample:
              $ref: '#/components/examples/methodNotAllowedErrorExample'
    tooManyRequestsResponse:
      description: Too Many Requests
      headers:
        Retry-After:
          description: How many seconds to wait before retrying.
          schema:
            type: integer
            example: 1
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/apiErrors'
          examples:
            tooManyRequestsExample:
              $ref: '#/components/examples/tooManyRequestsErrorExample'
    internalServerErrorResponse:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/apiErrors'
          examples:
            internalServerErrorExample:
              $ref: '#/components/examples/internalServerErrorErrorExample'
  schemas:
    accountId:
      type: number
      description: The ID of the Bandwidth App account making the CNAM dip.
      example: 1234567
    phoneNumber:
      type: string
      description: >-
        The calling number (ANI) to look up, in E.164 format, starting with '+'
        (plus) symbol.
      example: '+12345678901'
    dryRun:
      type: boolean
      description: >-
        If set to `true`, the request is performed as a dry run: a placeholder
        caller name is returned and the dip is

        not billed.
      example: false
    cnamInfo:
      type: object
      description: Caller-name information for the requested phone number.
      required:
        - links
        - data
        - errors
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/link'
          example:
            - href: >-
                https://api.bandwidth.com/api/v1/accounts/1234567/cnam/phone-numbers/%2B12345678901
              rel: self
              method: GET
        data:
          type: object
          nullable: true
          properties:
            callerName:
              type: string
              nullable: true
              description: >-
                The caller name returned by the CNAM vendor for the queried
                phone number.
              example: John Doe
            requestId:
              type: string
              nullable: true
              description: >-
                A Bandwidth-generated unique identifier for this dip. Use this
                value when referencing a specific

                lookup with Bandwidth support.
              example: b64b5e72-a850-4f38-98d4-5022cacd3f0f
            dryRun:
              type: boolean
              nullable: true
              description: >-
                `true` if this was a dry run (a placeholder caller name was
                returned and the dip was not billed),

                `false` otherwise.
              example: false
          example:
            callerName: John Doe
            requestId: b64b5e72-a850-4f38-98d4-5022cacd3f0f
            dryRun: false
        errors:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/apiError'
          example: []
    apiError:
      type: object
      required:
        - type
        - description
      properties:
        type:
          type: string
          description: >-
            A short, human-readable summary of the problem that SHOULD NOT
            change from occurrence to occurrence of the problem.
          example: request-error
        description:
          type: string
          description: >-
            A human-readable explanation that SHOULD be specific to this
            occurrence of the problem.
          example: There was an issue with a field in your request
        code:
          type: string
          nullable: true
          description: >-
            An application-specific error code for services with extensive error
            scenarios to supplement `description`.
          example: CA-0000
        source:
          type: object
          nullable: true
          properties:
            parameter:
              type: string
              description: A string indicating which URI query parameter caused the error.
              example: dryRun
            reference:
              type: string
              description: >-
                A string that references a resource ID or path to the resource
                (or non-existent resource) causing the error.
              example: /accounts/1234567/cnam/phone-numbers/%2B12345678901
            method:
              type: string
              description: A string indicating which HTTP method caused the error.
              example: GET
          example:
            method: GET
            reference: /accounts/1234567/cnam/phone-numbers/%2B12345678901
    link:
      type: object
      required:
        - href
        - rel
      properties:
        href:
          type: string
          description: URI of the link.
          example: >-
            https://api.bandwidth.com/api/v1/accounts/1234567/cnam/phone-numbers/%2B12345678901
        rel:
          type: string
          description: Specifies the relationship between this link and the resource.
          example: CnamInfo
        method:
          type: string
          description: HTTP method to be used.
          example: GET
    apiErrors:
      type: object
      required:
        - links
        - data
        - errors
      properties:
        links:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/link'
          example: []
        data:
          type: object
          nullable: true
          example: null
        errors:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/apiError'
  examples:
    cnamInfoExample:
      summary: Caller name found
      value:
        links:
          - href: >-
              https://api.bandwidth.com/api/v1/accounts/1234567/cnam/phone-numbers/%2B12345678901
            rel: self
            method: GET
        data:
          callerName: John Doe
          requestId: b64b5e72-a850-4f38-98d4-5022cacd3f0f
          dryRun: false
        errors: []
    badRequestErrorExample:
      summary: Bad Request
      value:
        data: null
        links: []
        errors:
          - type: bad-request
            code: CA-0000
            description: Malformed phone number.
            source:
              method: GET
              reference: /accounts/1234567/cnam/phone-numbers/%2B12345678901
    unauthorizedErrorExample:
      summary: Unauthorized
      value:
        data: null
        links: []
        errors:
          - type: unauthorized
            code: CA-0100
            description: You must be properly authenticated to access this resource.
            source:
              method: GET
              reference: /accounts/1234567/cnam/phone-numbers/%2B12345678901
    forbiddenErrorExample:
      summary: Forbidden
      value:
        data: null
        links: []
        errors:
          - type: forbidden
            code: CA-0200
            description: You do not have access to this resource.
            source:
              method: GET
              reference: /accounts/1234567/cnam/phone-numbers/%2B12345678901
    notFoundErrorExample:
      summary: Not Found
      value:
        data: null
        links: []
        errors:
          - type: resource-not-found
            code: CA-0300
            description: Resource not found.
            source:
              method: GET
              reference: /accounts/1234567/cnam/phone-numbers/%2B12345678901
    methodNotAllowedErrorExample:
      summary: Method Not Allowed
      value:
        data: null
        links: []
        errors:
          - type: method-not-allowed
            code: CA-0400
            description: POST is not supported at this URI.
            source:
              method: POST
    tooManyRequestsErrorExample:
      summary: Too Many Requests
      value:
        data: null
        links: []
        errors:
          - type: rate-limiting
            code: CA-0500
            description: Rate Limit Exceeded. Try again in 1 second.
    internalServerErrorErrorExample:
      summary: Internal Server Error
      value:
        data: null
        links: []
        errors:
          - type: internal-server-error
            code: CA-0600
            description: Encountered an unexpected error while processing your request.
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        Bearer authentication (also called token authentication) is an HTTP
        authentication scheme that involves security tokens called bearer
        tokens. The name “Bearer authentication” can be understood as “give
        access to the bearer of this token.” The client must send this token in
        the `Authorization` header when making requests to protected resources.


        - Example: `Authorization: Bearer <token>`


        Where `<token>` should be replaced with the token string without angle
        brackets.


        For more information, see the following guide:
        [Credentials](https://dev.bandwidth.com/docs/account/credentials/management)
security:
  - Bearer: []
tags:
  - name: CNAM
